package dev.orion.sdk.runtime

import dev.orion.sdk.AgentErrorCode
import dev.orion.sdk.AgentEventKind
import dev.orion.sdk.OrionException
import dev.orion.sdk.internal.NativeRun
import dev.orion.sdk.internal.asObject
import dev.orion.sdk.internal.requiredObject
import dev.orion.sdk.internal.requiredString
import dev.orion.sdk.internal.startCommand
import dev.orion.sdk.internal.toEffectResult
import dev.orion.sdk.internal.toModelRequest
import dev.orion.sdk.internal.toRunEvents
import dev.orion.sdk.internal.toRunResult
import dev.orion.sdk.model.CapabilitySupport
import dev.orion.sdk.model.ModelRegistry
import java.util.UUID
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonObject

/**
 * Coordinates host effects around the deterministic native run session.
 *
 * @param models model adapters available to every run executed by this runner.
 */
internal class Runner(private val models: ModelRegistry) {

    /**
     * Executes [agent] to completion for [input].
     *
     * @param agent immutable behavior and capability configuration.
     * @param input initial user message.
     * @param runId application-visible run identifier; generated by default.
     * @return the single terminal successful result.
     * @throws CancellationException when the calling coroutine is cancelled.
     * @throws OrionException when a model, tool, or native transition fails.
     */
    suspend fun run(
        agent: AgentDefinition,
        input: String,
        runId: String = "run-${UUID.randomUUID()}",
    ): RunResult = runStream(agent, input, runId)
        .toList()
        .filterIsInstance<RunResult>()
        .single()

    /**
     * Returns a cold stream of ordered lifecycle events followed by one result.
     *
     * Native resources exist only while the returned flow is collected and are
     * released on success, failure, or cancellation.
     *
     * @param agent immutable behavior and capability configuration.
     * @param input initial user message.
     * @param runId application-visible run identifier; generated by default.
     * @return cold flow that emits events followed by one result.
     */
    fun runStream(
        agent: AgentDefinition,
        input: String,
        runId: String = "run-${UUID.randomUUID()}",
    ): Flow<RunItem> = flow {

        validateCapabilities(agent)

        val native = try {
            NativeRun(startCommand(agent, input, runId))
        } catch (error: Exception) {
            throw normalizeNativeFailure(error, "native run rejected the agent definition", AgentErrorCode.INVALID_COMMAND)
        }

        native.use {
            var step = try {
                native.takeStep()
            } catch (error: Exception) {
                throw normalizeNativeFailure(error, "native run could not produce its first step")
            }
            val observedEvents = mutableListOf<RunEvent>()
            var terminalCause: Throwable? = null

            try {
                while (true) {
                    val newEvents = step.toRunEvents()
                    observedEvents += newEvents
                    newEvents.forEach { emit(it) }

                    step.toRunResult(observedEvents)?.let { result ->
                        emit(result)
                        return@flow
                    }

                    newEvents.lastRunFailure()?.let { failure ->
                        throw failure.toException(terminalCause)
                    }

                    if (newEvents.any { it.kind is AgentEventKind.RunCancelled }) {
                        throw OrionException(
                            message = "run cancelled",
                            code = AgentErrorCode.CANCELLED,
                            cause = terminalCause,
                        )
                    }

                    val effect = step["effect"]?.takeUnless { it is JsonNull }?.asObject("effect")
                        ?: throw OrionException("run suspended without an effect or terminal result")

                    val effectResult: JsonObject
                    try {
                        effectResult = executeHostEffect(agent, effect)
                    } catch (error: CancellationException) {
                        throw error
                    } catch (error: Exception) {
                        val failure = normalizeHostEffectFailure(effect, error)
                        terminalCause = error
                        step = try {
                            native.fail(failure.toProtocolJson())
                        } catch (nativeError: Exception) {
                            failure.addSuppressed(nativeError)
                            throw failure
                        }

                        continue
                    }

                    step = try {
                        native.resume(effectResult)
                    } catch (error: Exception) {
                        throw normalizeNativeFailure(error, "native run rejected the host effect result")
                    }
                }
            } catch (error: CancellationException) {
                cancelNativeRun(native, error)
                throw error
            }
        }

    }

    private fun validateCapabilities(agent: AgentDefinition) {

        val profile = try {
            models.resolve(agent.model).profile(agent.model)
        } catch (error: OrionException) {
            throw error
        } catch (error: Exception) {
            throw OrionException(
                message = "model capability profile could not be resolved",
                code = AgentErrorCode.CONFIGURATION,
                cause = error,
            )
        }

        if (agent.tools.isNotEmpty() && profile.toolCalling == CapabilitySupport.UNSUPPORTED) {
            throw OrionException(
                message = "model ${agent.model.provider}:${agent.model.model} does not support tool calling",
                code = AgentErrorCode.UNSUPPORTED_CAPABILITY,
            )
        }

        if (profile.structuredOutput == CapabilitySupport.UNSUPPORTED) {
            throw OrionException(
                message = "model ${agent.model.provider}:${agent.model.model} does not support structured output",
                code = AgentErrorCode.UNSUPPORTED_CAPABILITY,
            )
        }

    }

    private suspend fun executeHostEffect(agent: AgentDefinition, effect: JsonObject): JsonObject {

        val effectType = effect.requiredString("type")

        if (effectType != "call_model" && effectType != "execute_tool") {
            throw OrionException("native kernel requested unknown effect '$effectType'")
        }

        return if (effectType == "call_model") executeModelEffect(effect)
        else executeToolEffect(agent, effect)

    }

    private suspend fun executeModelEffect(effect: JsonObject): JsonObject {

        val request = effect.requiredObject("request").toModelRequest()
        val response = models.resolve(request.model).complete(request)

        return response.toEffectResult()

    }

    private suspend fun executeToolEffect(agent: AgentDefinition, effect: JsonObject): JsonObject {

        val call = effect.requiredObject("call")
        val toolName = call.requiredString("name")
        val tool = agent.tools.find { it.name == toolName }
            ?: throw OrionException(
                message = "model requested unregistered tool '$toolName'",
                code = AgentErrorCode.CONFIGURATION,
            )
        val content = tool.execute(call.requiredObject("arguments"))

        return buildJsonObject {
            put("type", "tool")
            putJsonObject("value") { put("content", content) }
        }

    }

    private suspend fun cancelNativeRun(native: NativeRun, error: CancellationException) {

        withContext(NonCancellable) {
            try {
                native.cancel()
            } catch (cancellationError: Exception) {
                error.addSuppressed(cancellationError)
            }
        }

    }

}

private const val MAX_ERROR_LENGTH: Int = 4_096

private fun List<RunEvent>.lastRunFailure(): AgentEventKind.RunFailed? =
    asReversed().firstNotNullOfOrNull { it.kind as? AgentEventKind.RunFailed }

private fun AgentEventKind.RunFailed.toException(cause: Throwable?): OrionException = OrionException(
    message = message,
    code = code,
    retryable = retryable,
    retryAfterMilliseconds = retryAfterMilliseconds,
    cause = cause,
)

private fun normalizeHostEffectFailure(effect: JsonObject, error: Exception): OrionException {

    if (error is OrionException) return error

    val isProviderFailure = effect.requiredString("type") == "call_model"

    return OrionException(
        message = if (isProviderFailure) "model provider request failed" else "tool execution failed",
        code = if (isProviderFailure) AgentErrorCode.PROVIDER else AgentErrorCode.TOOL,
        cause = error,
    )

}

private fun OrionException.toProtocolJson(): JsonObject = buildJsonObject {
    put("code", this@toProtocolJson.code.toProtocolName())
    put("message", this@toProtocolJson.message.orEmpty().take(MAX_ERROR_LENGTH))
    put("retryable", this@toProtocolJson.retryable)
    val retryAfterMilliseconds = this@toProtocolJson.retryAfterMilliseconds
    if (retryAfterMilliseconds == null) put("retry_after_ms", JsonNull)
    else put("retry_after_ms", retryAfterMilliseconds)
}

private fun AgentErrorCode.toProtocolName(): String = name.lowercase()

private fun normalizeNativeFailure(
    error: Exception,
    message: String,
    code: AgentErrorCode = AgentErrorCode.INVALID_STATE,
): OrionException = if (error is OrionException) {
    error
} else {
    OrionException(message = message, code = code, cause = error)
}
