from typing import Any

class NativeRun:
    def __init__(self, command: dict[str, Any]) -> None: ...
    def take_step(self) -> dict[str, Any]: ...
    def resume(self, result: dict[str, Any]) -> dict[str, Any]: ...
    def cancel(self) -> dict[str, Any]: ...
    def fail(self, error: dict[str, Any]) -> dict[str, Any]: ...
