"""Type declarations for the in-process PyO3 extension."""

from .model import JsonObject

class NativeRun:
    """Owns one Rust kernel session and its unread transition."""

    def __init__(self, command: JsonObject) -> None: ...
    def take_step(self) -> JsonObject: ...
    def resume(self, result: JsonObject) -> JsonObject: ...
    def cancel(self) -> JsonObject: ...
    def fail(self, error: JsonObject) -> JsonObject: ...
